### ISSUE TITLE
Linking fails after `pod install`

### ISSUE THREAD

**Issue by kerrmarin** [apotocki/icu4c-iosx#1]
Hey!

Thanks for the awesome effort getting ICU on CocoaPods :) -- I tried installing this on a project and when building, and I get the following warnings:

```
warning: [CP] Unable to find matching .xcframework slice in '/Users/kerrmarin/Developer/02-KERR/Test/Pods/../../icu4c-iosx/product/frameworks/icudata.xcframework icudata library ios-x86_64-simulator ios-arm64' for the current build architectures (arm64).
warning: [CP] Unable to find matching .xcframework slice in '/Users/kerrmarin/Developer/02-KERR/Test/Pods/../../icu4c-iosx/product/frameworks/icui18n.xcframework icui18n library ios-arm64 ios-x86_64-simulator' for the current build architectures (arm64).
warning: [CP] Unable to find matching .xcframework slice in '/Users/kerrmarin/Developer/02-KERR/Test/Pods/../../icu4c-iosx/product/frameworks/icuio.xcframework icuio library ios-x86_64-simulator ios-arm64' for the current build architectures (arm64).
warning: [CP] Unable to find matching .xcframework slice in '/Users/kerrmarin/Developer/02-KERR/Test/Pods/../../icu4c-iosx/product/frameworks/icuuc.xcframework icuuc library ios-x86_64-simulator ios-arm64' for the current build architectures (arm64).
```

They're not a big problem, however, I also get the following warnings and then error:

```
ld: warning: directory not found for option '-L/Users/kerrmarin/Library/Developer/Xcode/DerivedData/Test-dfmtaayewsbkhgaztpiotjisicck/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/icudata'
ld: warning: directory not found for option '-L/Users/kerrmarin/Library/Developer/Xcode/DerivedData/Test-dfmtaayewsbkhgaztpiotjisicck/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/icui18n'
ld: warning: directory not found for option '-L/Users/kerrmarin/Library/Developer/Xcode/DerivedData/Test-dfmtaayewsbkhgaztpiotjisicck/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/icuio'
ld: warning: directory not found for option '-L/Users/kerrmarin/Library/Developer/Xcode/DerivedData/Test-dfmtaayewsbkhgaztpiotjisicck/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/icuuc'
ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can get over it by linking the frameworks manually in the build phase, but I thought it would be better if it was possible to do this by updating the pod spec, or including something else on the podfile.

---

Unrelated, but I also added:

```
post_install do |installer_representation|
  project = installer_representation.pods_project
  project.targets.each do |target|
    if target.name == "icu4c-iosx"
      target.build_configurations.each do |config|
        target.build_settings(config.name)['VALID_ARCHS'] = "arm64 X86_64"
      end
    end
  end
end
```

to my podfile, so I didn't have to do the steps in the troubleshooting after each pod install. I think this can be avoided by adding:

```
s.pod_target_xcconfig = { 'VALID_ARCHS' => 'arm64 X86_64' }
```

to the podspec though. I see that a similar line is currently commented out, so I suspect there's a reason not to include it?

**Comment by apotocki** [comment]
Hi Kerr. Thank you for your feedback. I'll try to resolve this issue soon.

**Comment by kerrmarin** [comment]
Thanks @apotocki; here is an example project if you need one: https://github.com/kerrmarin/icu4c-test

**Comment by Aban** [comment]
Not sure if the same issue, but i am having errors about symbols not founds at linking stage. How did you solved it  @kerrmarin ?

**Comment by kerrmarin** [comment]
Not sure what your error is @Aban but if you create a new issue with the error you're getting we might be able to help :)

**Comment by kerrmarin** [comment]
@apotocki I was able to fix this issue by using:

```
post_install do |installer_representation|
  project = installer_representation.pods_project
  project.targets.each do |target|
    if target.name == "icu4c-iosx"
      target.build_configurations.each do |config|
        target.build_settings(config.name)['VALID_ARCHS'] = "$(ARCHS_STANDARD)"
      end
    end
  end
end
```

to my podfile. I think it would be awesome if we can get this done in the podspec though

**Comment by Aban** [comment]
oh thanks, i will create a new issue then

**Comment by apotocki** [comment]
I think I found a solution without the 'post_install' stage.  I tagged and pushed the new version '68.2.1' into github & cocoapods. Please try it. (Don't forget the 'pod update --verbose' step)  At least, I was able to pass the linking of https://github.com/kerrmarin/icu4c-test project without any manual fixes. (But I had to remove 'import icu4c-test' from Test.swift to compile the project)

**Comment by kerrmarin** [comment]
Thanks @apotocki; looks like it worked!
