### ISSUE TITLE
MAC-OSX deployment target - feature request

### ISSUE THREAD

**Issue by olekrisek** [apotocki/icu4c-iosx#11]
Hello, 
When linking to the framework, I receive messages that the deployment target is newer than that currently being linked. Is it possible to configure the build to target the build for a specific macOS deployment target, - I will also need different target for the Intel build and the arm build. I am currently in my project using 10.13 for intel, and 12.3 for arm (as arm wasn't available before 12.3). 

**Example from the Boost linking process**

```
ld: warning: object file (/Users/ole/Prosjekter/icu/icu4c-iosx/product/lib/libicudata.a[x86_64][2](icudt74l_dat.o)) was built for newer 'macOS' version (14.0) than being linked (10.13)
ld: warning: object file (/Users/ole/Prosjekter/icu/icu4c-iosx/product/lib/libicui18n.a[x86_64][6](bocsu.ao)) was built for newer 'macOS' version (14.0) than being linked (10.13)
ld: warning: object file (/Users/ole/Prosjekter/icu/icu4c-iosx/product/lib/libicui18n.a[x86_64][14](coleitr.ao)) was built for newer 'macOS' version (14.0) than being linked (10.13)
```

**Comment by apotocki** [comment]
I updated the build script a bit. Now you can specify the desired target versions for each platform by modifying appropriate variables in the "SETUP" section of build.sh. Just uncomment MACOSX_VERSION_ARM and MACOSX_VERSION_X86_64 for your case, remove previously built artifacts if they exist (product, *-build, *.success folders and files) and run 'scripts/build.sh'.

**Comment by apotocki** [comment]
I made the same build script changes for https://github.com/apotocki/boost-iosx. (Just in case.)

**Comment by olekrisek** [comment]
Thank you very much. I have built your boost-box and it went very well. Needed to install cocoapods and git-lfs, but after that the build went well. I am now about to compile icu-iox to load into the target application.

**Comment by olekrisek** [comment]
And also the target app now works well...
Thank you very much
