### ISSUE TITLE
Incompatibility with Cocoapods >1.16

### ISSUE THREAD

**Issue by jkuchar** [apotocki/icu4c-iosx#13]
This package depends on `.git` folder, therefore there is an incompatibility after version 1.16. -> https://github.com/CocoaPods/CocoaPods/issues/12674

**Comment by apotocki** [comment]
Isn't this a Cocoapods 1.16 bug? Or have we been banned from using git submodules since Cocoapods 1.16?

**Comment by jkuchar** [comment]
I'm not sure what is the intended behaviour of the cocoapods, however in the release notes there are no related deprecations mentioned. I would consider this a bug or unintentional BC break. https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0

<img width="897" alt="image" src="https://github.com/user-attachments/assets/893f4687-f4ee-49b6-bc15-9d3bd42519ce">

**Comment by apotocki** [comment]
I've removed the ICU submodule (for 75.1 and 76.1 versions). Now the ICU library is cloned directly in the build script. This must fix the problem.
