### ISSUE TITLE
Undefined Symbol for architecture arm64

### ISSUE THREAD

**Issue by Aban** [apotocki/icu4c-iosx#2]
Hello,

I have added this line to my `pod 'icu4c-iosx'` and after that i did `pod instal`, seems like everything went fine, but when i try to compile my project i am getting this errros:

`Undefined symbols for architecture arm64:
  "icu_68::UnicodeString::UnicodeString(char16_t const*)", referenced from:
      Font2::prepareToProcessArabicText(std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&) in Font2.o
  "vtable for icu_68::UObject", referenced from:`

Seems like the library is not being linked, do i need to do something else in order to use the library?

**Comment by apotocki** [comment]
Hi Aban,
Thank you for your feedback!
I've made some changes in podspec file. Please try the new version (68.2.1). You can do it by invoking 'pod update --verbose'. If your linking error doesn't disappear, could you please give me a minimal Xcode project that reproduces it?.

**Comment by Aban** [comment]
it seems to be working fine now, thanks!
