### ISSUE TITLE
Bitcode support?

### ISSUE THREAD

**Issue by kerrmarin** [apotocki/icu4c-iosx#5]
Hi,

I have used this library in a project and when archiving my (iOS) app, I get an error saying that:

```
ld: bitcode bundle could not be generated because '.../BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/icu4c-iosx/libicui18n.a(measunit.ao)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
```

Is there a way to enable bitcode when building this library? I can of course disable bitcode from my app, but I'd rather not to that if possible.

**Comment by apotocki** [comment]
Hi,
I tried to build ICU with bitcode support but failed. It seems that ICU codebase isn't compatible with bitcode generation at the moment. For me, bitcode is an absolutely optional feature that is hardly valuable, so I haven't found a time to find a solution. I'm sorry.

**Comment by kerrmarin** [comment]
Thanks @apotocki. I will open a bug with ICU. Out of curiosity, what command did you use to try and build with bitcode?

**Comment by apotocki** [comment]
Hi. I'm sorry I seemed to misle you. Today I successfully compiled the project with -fembed-bitcode flag. Also, I decreased the required minimum ios version to 13.4. All changes are in 71 branch and 71.1.2 tag

**Comment by kerrmarin** [comment]
That's great news, thanks for this @apotocki
