### ISSUE TITLE
Build x86_64 version for simulator as part of build in M1 mac

### ISSUE THREAD

**Issue by kerrmarin** [apotocki/icu4c-iosx#6]
Hi,

When including this library as a dependency of another pod spec, the linting phase of the other spec fails at link time because it can't find the symbols for x86_64. An extract of the error is:

```shell
Undefined symbols for architecture x86_64:
      "icu_71::ByteSink::GetAppendBuffer(int, int, char*, int, int*)", referenced from:
          vtable for icu_71::StringByteSink<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > in nmbr_icu(NMBRFormatter.o)
      "typeinfo for icu_71::ByteSink", referenced from:
          typeinfo for icu_71::StringByteSink<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > in nmbr_icu(NMBRFormatter.o)
      "icu_71::ByteSink::Flush()", referenced from:
          vtable for icu_71::StringByteSink<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > in nmbr_icu(NMBRFormatter.o)
      "icu_71::UMemory::operator delete(void*)", referenced from:
          icu_71::StringByteSink<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::~StringByteSink() in nmbr_icu(NMBRFormatter.o)
      "icu_71::Locale::Locale()", referenced from:
          icu_71::number::impl::MacroProps::MacroProps() in nmbr_icu(NMBRFormatter.o)
```

I tried to add support by duplicating the build step for the simulator with an x86_64 -arch flag, but it didn't work:

```shell
################### BUILD FOR SIM
ICU_IOS_SIM_BUILD_FOLDER=$ICU_VER_NAME-ios.sim-build
if [ ! -f $ICU_IOS_SIM_BUILD_FOLDER.success ]; then
echo preparing build folder $ICU_IOS_SIM_BUILD_FOLDER ...
if [ -d $ICU_IOS_SIM_BUILD_FOLDER ]; then
    rm -rf $ICU_IOS_SIM_BUILD_FOLDER
fi
cp -r $ICU4C_FOLDER $ICU_IOS_SIM_BUILD_FOLDER
echo "building icu (iOS: iPhoneSimulator)..."
pushd $ICU_IOS_SIM_BUILD_FOLDER/source

COMMON_CFLAGS="-arch x86_64 -fembed-bitcode-marker -isysroot $SIMSYSROOT/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=13.4 -I$SIMSYSROOT/SDKs/iPhoneSimulator.sdk/usr/include/"
./configure --disable-tools --disable-extras --disable-tests --disable-samples --disable-dyload --enable-static --disable-shared prefix=$INSTALL_DIR --host=$BUILD_ARC-apple-darwin --with-cross-build=$BUILD_DIR/$ICU_BUILD_FOLDER/source CFLAGS="$COMMON_CFLAGS" CXXFLAGS="$COMMON_CFLAGS -c -stdlib=libc++ -Wall --std=c++17" LDFLAGS="-stdlib=libc++ -L$SIMSYSROOT/SDKs/iPhoneSimulator.sdk/usr/lib/ -isysroot $SIMSYSROOT/SDKs/iPhoneSimulator.sdk -Wl,-dead_strip -lstdc++"

make -j$THREAD_COUNT
make install
popd
touch $ICU_IOS_SIM_BUILD_FOLDER.success 
fi
```

Would be great if the build script built all architectures available, so this pod spec can be used as a dependency in other specs.

**Comment by apotocki** [comment]
Hi,

try 71.1.3

**Comment by kerrmarin** [comment]
Hey @apotocki, thanks for the super quick reply + turnaround. Sorry I think I misled you when I mentioned the M1. The idea is that all architectures should be built in all scenarios, so for example on an M1 machine it should build x86 and arm, but on an x86 machine it should also build arm. The change on 71.1.3 works on an M1 but fails on an x86 (you can see the result here: https://github.com/kerrmarin/nmbr-icu/runs/6904948322?check_suite_focus=true)

**Comment by apotocki** [comment]
The project's primary purpose is to build all the binaries that, in principle, may be needed for ios development on the particular development machine. I understand why we can need x86_64 simulator builds on M1 Mac: we may want to run x86_64 Simulator through Rosetta on Mac M1. But the reverse situation is not applicable - It's impossible to run arm64 Simulator on x86_64 Mac. So I think it's useless to build arm64 Simulator binaries if a developer has Intel Mac.

**Comment by kerrmarin** [comment]
@apotocki fair enough. I appreciate your explanation. However this means that this library cannot be used as a dependency of another podspec, since the spec that depends on this one won't pass validation on an x86 machine. See the link in my previous comment for an example of an x86 machine trying to lint a very simple podspec that has this spec as a dependency. 

Your last release unblocked me however so feel free to close this issue.

Thanks again!

**Comment by apotocki** [comment]
Perhaps sometimes it's better to do things for the sake of convenience. Try 71.1.4

**Comment by kerrmarin** [comment]
Thanks @apotocki
