### ISSUE TITLE
Dynamic library?

### ISSUE THREAD

**Issue by kerrmarin** [apotocki/icu4c-iosx#7]
Is it possible to build icu as a dylib instead of a static framework? The reason I'm asking is because as a static framework it forces all other podspecs that depend on this spec to also be a static framework.

**Comment by apotocki** [comment]
What's the point of dynamic libraries in iOS if each app in iOS is in the self sandbox and they can not share the same user dynamic library apriori?

**Comment by kerrmarin** [comment]
Well the main advantage is that dynamic libraries can provide a faster launch experience for your app as the library will only be loaded when it is needed (or when the OS considers it is needed). Although historically this has been the opposite...

Another advantage is that if you have different targets (say an iMessage extension, a widget, a keyboard extension...) a dylib will be reused for all of them and a static lib will be duplicated, leading to larger binary size + the possibility of duplicated symbols.

There's also the historical baggage that for some time (before ABI stability) you could not create static libraries that included Swift code, although that's resolved now I suspect there's still some bias towards dynamic frameworks on iOS...

**Comment by kerrmarin** [comment]
I ended up wrapping this library in a pod that's not marked as static_framework to not have to force all dependencies of my library to be a static_framework - works well
